name: Update Figma Code Connect

on:
  push:
    paths:
      - src/*.figma.tsx
    branches:
      - main

env:
  NODE_VERSION: 20

jobs:
  code-connect:
    name: "React Code Connect"
    runs-on: [ onprem-k8s-arc, lnx-amd64, enterprise, std, self-hosted ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Install"
        run: npm i

      - name: "Publish"
        run: |
          npm config set noproxy "api.figma.com"
          npx figma connect publish --token "${{ secrets.FIGMA_ACCESS_TOKEN }}"
