import React from "react"
import { NeuButtonSelector } from "@neutron/react"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  NeuButtonSelector,
  "https://www.figma.com/design/gftI7XRpQvRyTAtu901Jqx/Neutron-Web-3.1----Base-Kit?node-id=4508-9004&t=dfOdDnnleUneqiIG-4",
  {
    props: {
      color: figma.enum("Color", {
        Orange: "orange",
        Blue: "blue",
      }),

      track: figma.enum("Background", {
        Plain: "plain",
        Gray: "gray",
      }),

			size: figma.enum("Size", {
        Default: "default",
        Small: "small",
      }),

			children: figma.children(".Single Selector Units")
    },

		example: ({ color, size, track, children } ) => {
			return(
				<NeuButtonSelector
					unit="group"
					kind="single"
					color={ color }
					size={ size }
					track={ track }
	
					onNeuForm={ (ev) => {} }
					onNeuChange={ (ev) => {} }
					onNeuFocus={ (ev) => {} }
					onNeuBlur={ (ev) => {} }
				>
					{ children }
				</NeuButtonSelector>
			)
		},
	}
)	