import React from "react"
import { NeuTab, NeuIcon } from "@neutron/react"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(NeuTab, "https://www.figma.com/design/gftI7XRpQvRyTAtu901Jqx/Neutron-Web-3.1----Base-Kit?node-id=8608-35690&t=0vcUtgK6keKLRvT6-4", {
    props: {
      label: figma.string("Label"),
      iconStart: figma.boolean("Icon Start", {
        true: <NeuIcon>YOUR-ICON-HERE</NeuIcon>,
        false: undefined
      }),

      dropdown: figma.boolean("Dropdown"), //  
      mode: figma.enum("Mode", {
        Dark: "dark",
        Light: "light",
      }),
      color: figma.enum("Color", {
        Blue: "blue",
        Orange: "orange",
      }),
      size: figma.enum("Size", {
        Default: undefined,
        Small: "small",
      }),
      isActive: figma.enum("State", {
        Resting: undefined,
        Hover: undefined,
        Active: true,
      }),
    },
    example: ({mode, color, size, isActive, iconStart, label}) => {
      return(
        <NeuTab
          value= { "VALUE" } 
          kind= { mode }
          color= { color }
          size= { size }
          active= { isActive }
        >{ iconStart }{ label }</NeuTab>
      )
    }
  },
)
