import React from "react"
import { NeuInput } from "@neutron/react"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  NeuInput,
  "https://www.figma.com/design/gftI7XRpQvRyTAtu901Jqx/Neutron-Web-3.1----Base-Kit?node-id=4805-17269&t=ce87M02MwQF37K0T-4",
  {
    props: {
      isOptional: figma.boolean("Optional", {
        true: undefined,
        false: true,
      }),
      helperText: figma.boolean("Helper Text", {
        true: "...",
        false: undefined,
      }),
      content: figma.enum("Content", {
        Text: "text",
        "Content Slot": "content-slot",
      }),
      state: figma.enum("State", {
        Inactive: undefined,
        Active: undefined,
        Error: undefined,
        "Active Error": undefined,
        Disabled: true,
      }),
    },
    example: ({content, state, helperText, isOptional}) => {
      return( 
        <NeuInput
          value= "VALUE"
          type= "text" 
          disabled= { state } 
          tip= { helperText}
          invalid= { helperText }
          required= { isOptional }  

            onNeuForm={ (ev) => {} }
            onNeuFocus={ (ev) => {} }
            onNeuBlur={ (ev) => {} }
        >{ content }</NeuInput>
      )
    }
  },
)
