import React from "react"
import { NeuTooltip } from "@neutron/react"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  NeuTooltip,
  "https://www.figma.com/design/gftI7XRpQvRyTAtu901Jqx/Neutron-Web-3.1----Base-Kit?node-id=660-1002&t=0vcUtgK6keKLRvT6-4",
  {
    props: {
      mode: figma.enum("Mode", {
        Light: "light",
      }),
    },
    example: (props) => {
      return (
        <NeuTooltip
          tip= "..." 
          highlight= { false }
        >TRIGGER-GOES-HERE</NeuTooltip>
      )
    }
  },
)
